
USA_CODE_NAME = {
    "AL": "Alabama",
    "AK": "Alaska",
    "AS": "American Samoa",
    "AZ": "Arizona",
    "AR": "Arkansas",
    "CA": "California",
    "CO": "Colorado",
    "CT": "Connecticut",
    "DE": "Delaware",
    "DC": "District Of Columbia",
    "FM": "Federated States Of Micronesia",
    "FL": "Florida",
    "GA": "Georgia",
    "GU": "Guam",
    "HI": "Hawaii",
    "ID": "Idaho",
    "IL": "Illinois",
    "IN": "Indiana",
    "IA": "Iowa",
    "KS": "Kansas",
    "KY": "Kentucky",
    "LA": "Louisiana",
    "ME": "Maine",
    "MH": "Marshall Islands",
    "MD": "Maryland",
    "MA": "Massachusetts",
    "MI": "Michigan",
    "MN": "Minnesota",
    "MS": "Mississippi",
    "MO": "Missouri",
    "MT": "Montana",
    "NE": "Nebraska",
    "NV": "Nevada",
    "NH": "New Hampshire",
    "NJ": "New Jersey",
    "NM": "New Mexico",
    "NY": "New York",
    "NC": "North Carolina",
    "ND": "North Dakota",
    "MP": "Northern Mariana Islands",
    "OH": "Ohio",
    "OK": "Oklahoma",
    "OR": "Oregon",
    "PW": "Palau",
    "PA": "Pennsylvania",
    "PR": "Puerto Rico",
    "RI": "Rhode Island",
    "SC": "South Carolina",
    "SD": "South Dakota",
    "TN": "Tennessee",
    "TX": "Texas",
    "UT": "Utah",
    "VT": "Vermont",
    "VI": "Virgin Islands",
    "VA": "Virginia",
    "WA": "Washington",
    "WV": "West Virginia",
    "WI": "Wisconsin",
    "WY": "Wyoming"
}

USA_NAME_NUMBER = {
    "Alabama" : 1,
    "Alaska" : 2, 
    "American Samoa" : 3,
    "Arizona" : 4,
    "Arkansas" : 5,
    "California" : 6,
    "Colorado" : 7,
    "Connecticut": 8,
    "Delaware": 9,
    "District of Columbia": 10,
    "District Of Columbia": 10,
    "Federated States Of Micronesia": 11,
    "Florida": 12,
    "Georgia": 13,
    "Guam": 14,
    "Hawaii": 15,
    "Idaho": 16,
    "Illinois": 17,
    "Indiana": 18,
    "Iowa": 19,
    "Kansas": 20,
    "Kentucky": 21,
    "Louisiana": 22,
    "Maine": 23,
    "Marshall Islands": 24,
    "Maryland": 25,
    "Massachusetts": 26,
    "Michigan": 27,
    "Minnesota": 28,
    "Mississippi": 29,
    "Missouri": 30,
    "Montana": 31,
    "Nebraska": 32,
    "Nevada": 33,
    "New Hampshire": 34,
    "New Jersey": 35,
    "New Mexico": 36,
    "New York": 37,
    "North Carolina": 38,
    "North Dakota": 39,
    "Northern Mariana Islands": 40,
    "Ohio": 41,
    "Oklahoma": 42,
    "Oregon": 43,
    "Palau": 44,
    "Pennsylvania": 45,
    "Puerto Rico": 46,
    "Rhode Island": 47,
    "South Carolina": 48,
    "South Dakota": 49,
    "Tennessee": 50,
    "Texas": 51,
    "Utah": 52,
    "Vermont": 53,
    "Virgin Islands": 54,
    "Virginia": 55,
    "Washington": 56,
    "West Virginia": 57,
    "Wisconsin": 58,
    "Wyoming": 59
}
